### ISSUE TITLE
Designer exports all files with root owner

### ISSUE THREAD

**Issue by corot** [rapyuta-robotics/alica#232]
**Describe the bug**
Designer exports all files with root owner. If the files already exist, it overwrites them again with root owner.

**Expected behaviour**
Export with current user as owner

**System information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: rr_devel

**Comment by abhi1287** [comment]
@athish-t  you were trying somethings to fix this. Did you find any solution?

**Comment by athish-t** [comment]
I haven't tried to find a solution yet. Let me add it to wrike so i don't forget
