### ISSUE TITLE
Minor tutorial turtlesim README.md bug

### ISSUE THREAD

**Issue by triccyx** [rapyuta-robotics/alica#258]
**Describe the bug**
Tutorial README.md minor:
[README.md](https://github.com/rapyuta-robotics/alica/tree/rr_devel/supplementary/alica_ros_turtlesim#readme)

**To Reproduce**

**Expected behaviour**
In section `8.1 Build`
Instead of:
```bash
cd catkin_ws
source /opt/ros/$(ls /opt/ros)/setup.bash
source ./devel/setup.bash
catkin build alica_ros_turtlesim
```
use:
```bash
cd catkin_ws
source /opt/ros/$(ls /opt/ros)/setup.bash
catkin build alica_ros_turtlesim
source ./devel/setup.bash
```

**Plans**

**System information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: rr_devel

**Additional context**

**Comment by Dale-Koenig** [comment]
Feel free to make a PR

**Comment by triccyx** [comment]
As PR https://github.com/rapyuta-robotics/alica/pull/320
